### ISSUE TITLE
Model Instances Not Deploying in v3

### ISSUE THREAD

**Issue by david-saeger** [awslabs/LISA#101]
After tearing down all v2 infrastructure and re deploying. All Stacks report CREATE_COMPLETE status. After deploying none of the models I have in configuration have compute instances attached and there are no registeredModels.

My config looks like this 

```yaml
env: dev
dev:
  appName: lisa
  deploymentName: owl
  accountNumber: ######
  region: #######
  deploymentStage: dev
  removalPolicy: destroy
  runCdkNag: false
  systemBanner:
    text: 'Lisa'
    backgroundColor: blue
    fontColor: white
  s3BucketModels: owl-models
  mountS3DebUrl: https://s3.amazonaws.com/mountpoint-s3-release/latest/x86_64/mount-s3.deb
  accountNumbersEcr:
    - #######
  deployRag: true
  lambdaConfig:
    pythonRuntime: PYTHON_3_10
    logLevel: DEBUG
    vpcAutoscalingConfig:
      provisionedConcurrentExecutions: 5
      minCapacity: 1
      maxCapacity: 50
      targetValue: 0.80
      cooldown: 30
  authConfig:
    authority: https://cognito-idp.us-gov-west-1.amazonaws.com/us-gov-west-1_iG9gEGqj1
    clientId: 3ag8sc91egsi4f12kju3lfdf1p
    adminGroup: admin
    jwtGroupsProperty: cognito:groups
  logLevel: DEBUG
  restApiConfig:
    apiVersion: v2
    instanceType: m5.large
    containerConfig:
      image:
        baseImage: python:3.9
        path: lib/serve/rest-api
        type: asset
      healthCheckConfig:
        command: ['CMD-SHELL', 'exit 0']
        interval: 10
        startPeriod: 30
        timeout: 5
        retries: 3
    autoScalingConfig:
      minCapacity: 1
      maxCapacity: 1
      cooldown: 60
      defaultInstanceWarmup: 60
      metricConfig:
        AlbMetricName: RequestCountPerTarget
        targetValue: 1000
        duration: 60
        estimatedInstanceWarmup: 30
    loadBalancerConfig:
      sslCertIamArn: arn:aws-us-gov:iam::189215246007:server-certificate/owl-dev
      healthCheckConfig:
        path: /health
        interval: 60
        timeout: 30
        healthyThresholdCount: 2
        unhealthyThresholdCount: 10
      domainName:
  ragRepositories:
    - repositoryId: pgvector-rag
      type: pgvector
      rdsConfig:
        username: postgres
 
  ragFileProcessingConfig:
    chunkSize: 512
    chunkOverlap: 51
  ecsModels:
    - modelName: mistralai/Mistral-7B-Instruct-v0.2
      modelId: mistral7b
      deploy: true
      streaming: true
      modelType: textgen
      instanceType: g4dn.2xlarge
      inferenceContainer: tgi
      containerConfig:
        image:
          baseImage: ghcr.io/huggingface/text-generation-inference:2.0.4
          path: lib/serve/ecs-model/textgen/tgi
          type: asset
        sharedMemorySize: 2048
        healthCheckConfig:
          command: ['CMD-SHELL', 'exit 0']
          interval: 10
          startPeriod: 30
          timeout: 5
          retries: 3
        environment:
          MAX_CONCURRENT_REQUESTS: 128
          MAX_INPUT_LENGTH: 1024
          MAX_TOTAL_TOKENS: 2048
          RUST_BACKTRACE: 1
      autoScalingConfig:
        minCapacity: 1
        maxCapacity: 1
        defaultInstanceWarmup: 180
        cooldown: 420
        metricConfig:
          AlbMetricName: RequestCountPerTarget
          targetValue: 30
          duration: 60
          estimatedInstanceWarmup: 330
      loadBalancerConfig:
        healthCheckConfig:
          path: /health
          interval: 60
          timeout: 30
          healthyThresholdCount: 2
          unhealthyThresholdCount: 10


    - modelName: intfloat/e5-large-v2
      modelId: e5v2
      deploy: true
      modelType: embedding
      instanceType: g4dn.xlarge
      inferenceContainer: tei
      containerConfig:
        image:
          baseImage: ghcr.io/huggingface/text-embeddings-inference:turing-latest
          path: lib/serve/ecs-model/embedding/tei
          type: asset
        sharedMemorySize: 2048
        healthCheckConfig:
          command: ['CMD-SHELL', 'exit 0']
          interval: 10
          startPeriod: 30
          timeout: 5
          retries: 3
        environment:
          MAX_CONCURRENT_REQUESTS: 512
          MAX_CLIENT_BATCH_SIZE: 1024
          MAX_BATCH_TOKENS: 16384
          RUST_BACKTRACE: 1
      autoScalingConfig:
        minCapacity: 1
        maxCapacity: 1
        cooldown: 420
        defaultInstanceWarmup: 180
        metricConfig:
          AlbMetricName: RequestCountPerTarget
          targetValue: 60
          duration: 60
          estimatedInstanceWarmup: 330
      loadBalancerConfig:
        healthCheckConfig:
          path: /health
          interval: 30
          timeout: 10
          healthyThresholdCount: 2
          unhealthyThresholdCount: 10
 
  litellmConfig:
    litellm_settings:
      telemetry: false # Don't try to send telemetry to LiteLLM servers.
    general_settings:
      master_key: xxxxxxxxxxxx1 # A key is required for model management purposes
```

**Comment by petermuller** [comment]
Hi David, unfortunately, that is expected- we called that out here as part of the v2 -> v3 migration docs [here](https://github.com/awslabs/LISA?tab=readme-ov-file#breaking-changes-in-v2-to-v3-migration)

The good news though is with the configuration of an "admin" group in your IDP, you will then have access to the Model Management tab for adding the models with these same params (except the `path` component of `containerConfig.image.path`, which after scanning the readme file, i see was removed 😢 ) That behavior here, outlining that the "path" is now relative to the ecs-model directory instead of the repository root: https://github.com/awslabs/LISA/commit/8a08f9bb45fa7dfef4e49a842988c8fda03be1a7#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R56-R60

and I'll get a new PR out to add that information back because that's an important one 😅

**Comment by petermuller** [comment]
Added as part of the tagged commit and now referenced here https://github.com/awslabs/LISA?tab=readme-ov-file#creating-a-model-admin-api

**Comment by david-saeger** [comment]
Ahh darn. Should have read the docs closer! Apologies!

**Comment by david-saeger** [comment]
can confirm I was able to add a model through the API. Strangely the UI is not showcasing a model management tab despite the fact that I have updated added a user group "admin" and set it in authconfig in the LISA configuration

```
  authConfig:
    authority: xxxxx
    clientId: xxxxx
    adminGroup: admin
    jwtGroupsProperty: cognito:groups
```

This is not a blocker for me but just noting in case it is a broader issue or perhaps I am missing some info on how to navigate to the administrative panel.
