### ISSUE TITLE
Not creating ECS models

### ISSUE THREAD

**Issue by alu-85** [awslabs/LISA#237]
Hello

I have deployed LISA and connected it to IdP.  Models are downloaded to the S3 bucket that specified in the LISA config and the infrastructure spins up without error.  However, there are no containerised models present in ECS - the cluster instance is created but there are 0 containers.  Similarly the associated model repo is empty.  I can log into the Model Management page via the UI and attempted to create a model there, however the UI fails to load the instance types in the drop down and I can get no further there.

So the issue is the models detailed in the configuration as below do not seem to be deployed:
```
 ecsModels:
  - modelName: mistralai/Mistral-7B-Instruct-v0.2
    inferenceContainer: tgi
    baseImage: ghcr.io/huggingface/text-generation-inference:2.0.1
  - modelName: bigcode/starcoder2-15b
    inferenceContainer: tgi
    baseImage: ghcr.io/huggingface/text-generation-inference:2.0.1
  - modelName: meta-llama/Llama-3.1-70B-Instruct
    inferenceContainer: tgi
    baseImage: ghcr.io/huggingface/text-generation-inference:2.0.1
```

I can run `make checkModels` and get the following output:

```
Found 4 safetensors for model: mistralai/Mistral-7B-Instruct-v0.2 in bucket: hf-models-sourcegraph.
Found 15 safetensors for model: bigcode/starcoder2-15b in bucket: hf-models-sourcegraph.
Found 18 safetensors for model: meta-llama/Llama-3.1-70B-Instruct in bucket: hf-models-sourcegraph.
```

The CDK output gives no errors - can someone direct any areas that might help to track down this issue?  

Additional info for the custom config: 
- it's an internal deployment
- I specify the ssl certificate
- I have tried deploying by specifying private subnets in the config and without specifying and get the same result
- Additionally I specify the VPC, region, account number, s3 bucket and litellm key
